site_name: Klipper Maintenance
site_url: https://3dcoded.github.io/KlipperMaintenance
repo_url: https://github.com/3dcoded/KlipperMaintenance
edit_uri: blob/docs/docs/
plugins:
  - search
  - autolinks
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
extra:
  analytics:
    provider: google
    property: G-QN601HS43W
theme:
  features:
      - content.action.edit
      - navigation.expand
      - navigation.instant
      - navigation.instant.prefetch
      - content.code.copy
      - search.suggest
      - search.highlight
      - search.share
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - install.md
  - config.md
  - gcodes.md